### ISSUE TITLE
Implement drag and drop

### ISSUE THREAD

**Issue by apandada1** [rafaelmardojai/WebfontKitGenerator#15]
It would be nice to be able to drag and drop an OTF/TTF file (instead of manually selecting), and then convert it with a single click.

**Comment by rafaelmardojai** [comment]
I have implemented drag and drop locally, but it wouldn't work in flatpak until GTK4.

**Comment by rafaelmardojai** [comment]
@apandada1 I have added drag and drop support to master, could you test it without flatpak?

**Comment by apandada1** [comment]
Drag and Drop does not seem to work in Manjaro XFCE (fully updated, has libhandy 1.2), and there is no error message in the Terminal. Do I need any dependency for drag and drop?

I will see if it works, with other DEs of Manjaro.

**Comment by rafaelmardojai** [comment]
There was something wrong with the path parsing from the drag and drop.

It's working fine for me in flatpak with home or host access.

**Comment by apandada1** [comment]
Still does not work without flatpak (meson build) in Manjaro XFCE. I would like to test the flatpak in XFCE.

How do I get latest master branch with flatpak?

**Comment by rafaelmardojai** [comment]
You can download the flatpak artifact from the latest github commit: https://github.com/rafaelmardojai/WebfontKitGenerator/suites/2326805504/artifacts/48986058

**Comment by rafaelmardojai** [comment]
> Still does not work without flatpak (meson build) in Manjaro XFCE. I would like to test the flatpak in XFCE.

Interesting, you even don't see the green border around the window when you drag something?

**Comment by apandada1** [comment]
> Interesting, you even don't see the green border around the window when you drag something?

In Manjaro XFCE (v4.16), both AUR (with meson) and flatpak versions do not "see" the font when I try to drag and drop. XFCE 4.16 is based on GTK3, I don't know why this is happening.

I installed the flatpak version in Linux Mint Cinnamon. There the app shows a green border when I drag a font to it. However, it cannot load the font due to a "reading permission" issue.

**Comment by rafaelmardojai** [comment]
> In Manjaro XFCE (v4.16), both AUR (with meson) and flatpak versions do not "see" the font when I try to drag and drop. XFCE 4.16 is based on GTK3, I don't know why this is happening.

Mmh, very strange, we're using the standard GTK drag and drop handing. Can you try to reproduce it with other GTK app? [Curtail](https://github.com/Huluti/Curtail) for example.

> I installed the flatpak version in Linux Mint Cinnamon. There the app shows a green border when I drag a font to it. However, it cannot load the font due to a "reading permission" issue.

That's expected, you need to give it `home` access with a flatpak override using Flatseal or running:
`sudo flatpak override com.rafaelmardojai.WebfontKitGenerator --filesystem=home`

**Comment by apandada1** [comment]
Curtail has the _same issue_ in Manjaro XFCE, both the AUR (native build with meson) and flatpak versions.

The window is not focused when I try to drag something over it. I also tried enabling focus follows mouse, but it does not help (when I drag the font, focus does not follow mouse, the window under the mouse remains unfocused). 
However, drag and drop works between desktop to XFCE file manager Thunar (which now uses GTK3).

It would be a good idea to open a bug report with XFCE. 
I don't know about the details of the GTK drag and drop APIs which are not working in XFCE. I would open the initial bug report, and would need your help to fill in some technical details. Meanwhile, I would ask a question in the Manjaro forum, to know which component of XFCE should the bug be reported against.

**Comment by rafaelmardojai** [comment]
Good to know it isn't a Webfont Kit Generator bug. I will release a new version in the next days.

**Comment by apandada1** [comment]
Drag and drop also does not work in Xubuntu 21.04, but it works in Manjaro KDE. It must be an XFCE specific issue.

**Comment by apandada1** [comment]
@rafaelmardojai Drag and Drop works with [Cozy](https://github.com/geigi/cozy) in Manjaro XFCE.

**Comment by rafaelmardojai** [comment]
Well the code is the same, the difference is that it uses the window as target instead of a GtkBox. But probably works like a workaround, I will try it later.

**Comment by rafaelmardojai** [comment]
@apandada1 could you test last commit?

**Comment by apandada1** [comment]
Unfortunately, it still does not work (behavior remains the same). Tested in Manjaro XFCE with latest git code.

**Comment by rafaelmardojai** [comment]
Now we're almost mimicking the Cozy implementation. Could you try again?
In case it still doesn't work, I will revisit this later.

**Comment by apandada1** [comment]
Still does not work.

But :+1: for the effort.

**Comment by rafaelmardojai** [comment]
The main difference is here right now:
https://github.com/rafaelmardojai/webfont-kit-generator/blob/5b6df2a8fcd392472aa6105c1888ec64fb0bee09/src/window.py#L81

Could you change `Gtk.DestDefaults.ALL` with `Gtk.DestDefaults.MOTION | Gtk.DestDefaults.HIGHLIGHT | Gtk.DestDefaults.DROP` and test if things change?

**Comment by apandada1** [comment]
Still did not work :-(

**Comment by rafaelmardojai** [comment]
> Still did not work :-(

Yep, that's what I supposed. Then our implementation are pretty the same.  I don't know why it works fine on XFCE.

**Comment by apandada1** [comment]
There is a recent pull which fixes this in Curtail (https://github.com/Huluti/Curtail/pull/79), and I verified that [this commit](https://github.com/Huluti/Curtail/pull/79/commits/c0f26b1fda0816068face8dd2efc78c3dea1fd3f) fixes it in Webfont-kit-generator too.

**Comment by rafaelmardojai** [comment]
Thanks! Fix pushed.

**Comment by apandada1** [comment]
> Thanks! Fix pushed.

You probably forgot to push the fix. There are no new commits here https://github.com/rafaelmardojai/webfont-kit-generator/commits/master

**Comment by rafaelmardojai** [comment]
Yeah, should be online now :P
