### ISSUE TITLE
Initial design review

### ISSUE THREAD

**Issue by bertob** [rafaelmardojai/WebfontKitGenerator#2]
First of all, thanks for this very cool app!

I just built in in Builder, and here are a few things I found that could be improved:

![image](https://user-images.githubusercontent.com/1908896/82846050-4a55ea80-9ee7-11ea-9285-bef027a52ed5.png)

The initial state is a bit empty, I'd add a large symbolic icon, e.g. the app symbolic or `text-bold-symbolic` between the header and the button.

![image](https://user-images.githubusercontent.com/1908896/82845291-38267d00-9ee4-11ea-9c41-ba2d05c47c5f.png)

I think the output options dialog could be a bit less compact, e.g. like this:

![image](https://user-images.githubusercontent.com/1908896/82845776-13cba000-9ee6-11ea-990d-963a1a80cd53.png)

If technically possible, something like this could be potentially interesting:

![image](https://user-images.githubusercontent.com/1908896/82845879-8b99ca80-9ee6-11ea-9664-f25537a7ef89.png)

It feels odd that I get a file chooser when clicking "Generate". Perhaps the output directory could be set in the output options instead? 

![image](https://user-images.githubusercontent.com/1908896/82846180-e67ff180-9ee7-11ea-966a-d1f34b8c5a34.png)

It's a bit weird that there's neither cancel nor close during the generation process. I tried with a file that didn't work, so the app got stuck in a limbo state you can only recover from by closing the app, which is not great.

I'd have a "Cancel" button during the generation process which goes back to the regular app window.

On both these views I'd increase vertical spacing between elements, especially below headers and between sections, so they don't looks so cramped:

![image](https://user-images.githubusercontent.com/1908896/82844523-15df3000-9ee1-11ea-9c97-1a3b8d10c788.png)

I'd also add a bit of padding inside that sourceview if possible, e.g. 6px or so.

![image](https://user-images.githubusercontent.com/1908896/82844536-20012e80-9ee1-11ea-8b09-16b76802d0ae.png)

Also, I'd make all the headers ultra-bold, looks cooler :P

**Comment by rafaelmardojai** [comment]
I have achieved most of your suggestions, please test latest commits when you have time.

**Comment by bertob** [comment]
Very nice, I really like the new subsetting settings!

A few more things I noticed while trying it:

The file chooser button feels a bit meh here, I'd suggest trying an entry with a "Browse..." button connected to it.

![image](https://user-images.githubusercontent.com/1908896/83002456-605dcb00-a00d-11ea-9e33-fc7994f410a0.png)

Example (from App Icon Preview):

![image](https://user-images.githubusercontent.com/1908896/83002537-77042200-a00d-11ea-81b6-2854a72d7b8d.png)



This view feels a bit off-balance layout-wise, I think largely because the top and bottom are empty, while the progressbar in the middle is taking up the full width. I'd try putting the progressbar in an HdyColumn with a max width around 600px or so, so it never takes up the full width. 

I'd also maybe not style the cancel button as destructive, it looks a bit too prominent (and you're not really losing data with it).

![image](https://user-images.githubusercontent.com/1908896/83001010-6ce12400-a00b-11ea-98aa-52df789e6277.png)

After generation is complete it would be nice if there was an easy way to open the directory with the generated files. I'd try adding a "Open in Files" button below the code snippets.

![image](https://user-images.githubusercontent.com/1908896/83000811-2d1a3c80-a00b-11ea-88f1-76752fa0a82a.png)

**Comment by rafaelmardojai** [comment]
> The file chooser button feels a bit meh here, I'd suggest trying an entry with a "Browse..." button connected to it.

Be aware it will show the ugly `/run/user/1001/doc/xxxxxx/foo` path. I don't want to set `--filesystem=home` permission.

**Comment by bertob** [comment]
Hmm yeah, that's not great. Let's maybe leave it as-is, and see if it can be addressed at the Flatpak level, because I can imagine a lot of apps wanting this kind of pattern.

**Comment by rafaelmardojai** [comment]
Which one looks better to you?
![Captura de pantalla de 2020-05-27 12-34-47](https://user-images.githubusercontent.com/6210397/83053549-8045bc80-a016-11ea-8144-b8757f8f79d0.png)

**Comment by rafaelmardojai** [comment]
I have implemented all of your suggestions.

Currently the "Open in Files" button isn't working. Since i can't get `Gtk.show_uri_on_window` to work with the folder URI provided by the sandbox.

**Comment by bertob** [comment]
Hmm yeah, this is definitely not great :/

![image](https://user-images.githubusercontent.com/1908896/83128677-0972f700-a0dc-11ea-9093-ab8a00749987.png)

Since that path doesn't give us any useful information and (I assume) can't be edited, perhaps we could just have a label with the folder name instead, e.g. like this:

![image](https://user-images.githubusercontent.com/1908896/83129207-bc435500-a0dc-11ea-814c-12a8a2fce2a8.png)

> Currently the "Open in Files" button isn't working. Since i can't get Gtk.show_uri_on_window to work with the folder URI provided by the sandbox.

Hmm so, is this not possible at all with the current permissions or something we could work around somehow?

**Comment by rafaelmardojai** [comment]
Enabling access to `home` should fix all the issues. But i don't think that's ideal.

I found something here: flatpak/xdg-desktop-portal#95

**Comment by rafaelmardojai** [comment]
I have implemented the new "Output directory".

**Comment by bertob** [comment]
Nice :+1:

I think overall this app looks really good now, might be worth making a new release soon :)

One thing I think could still be improved a bit is the welcome screen, the single symbolic is still not great here:

![image](https://user-images.githubusercontent.com/1908896/83240809-32f25800-a19a-11ea-8c0c-ccf001aea86c.png)

Perhaps we could try a simple illustration, e.g. something like this?

![image](https://user-images.githubusercontent.com/1908896/83272768-e0319400-a1cb-11ea-8f32-6238096238da.png)

This is the SVG: [webfont-splash.zip](https://github.com/rafaelmardojai/WebfontKitGenerator/files/4702461/webfont-splash.zip)

**Comment by rafaelmardojai** [comment]
> Perhaps we could try a simple illustration, e.g. something like this?

**Comment by rafaelmardojai** [comment]
> Perhaps we could try a simple illustration, e.g. something like this?

Nice, I just implemented it.

> I think overall this app looks really good now, might be worth making a new release soon :)

I'm aiming to fix the "Open in Files" button before a new release. Also a proper icon would be awesome (#1).

**Comment by bertob** [comment]
Sweet, that looks much better!

> I'm aiming to fix the "Open in Files" button before a new release.

If it doesn't work due to the sandboxing thing feel free to remove it, at least for now.

Happy to help with a new icon, but I wouldn't block the release on it, you can always make another one later :)

**Comment by rafaelmardojai** [comment]
Yeah. You are right. Current changes are enough for a new release.
I'm probably releasing `0.2.0` tomorrow.

**Comment by rafaelmardojai** [comment]
**0.2.0** has been released.
Thanks for your feedback and suggestions! The app is looking very neat now.

I'm closing this. Feel free to open new issues if you find other things to polish.
